import type { Metadata } from "next"; // ✅ To'g'ri import

import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
interface LayoutProps {
  children: React.ReactNode;
}


const inter = Inter({
  variable: "--inter",
  subsets: ["latin"],
  weight:["100", "300" ,"400", "500" , '600' ,"700"]
});

export const metadata: Metadata = {
  title: "Tasklarim",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
        <ToastContainer
          position="top-right"
          autoClose={1000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}